name: CI Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run unit tests
        env:
          VITE_EVBP_MUSIC_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          VITE_EVBP_MUSIC_CLOUDFLARE_TURNSTILE_SITE_KEY: ${{ secrets.CLOUDFLARE_TURNSTILE_SITE_KEY }}
          VITE_EVBP_MUSIC_CLOUDFLARE_TURNSTILE_SECRET_KEY: ${{ secrets.CLOUDFLARE_TURNSTILE_SECRET_KEY }}
        run: npm run test

      - name: Run Cucumber tests
        env:
          VITE_EVBP_MUSIC_BASE_URL: ${{ secrets.BASE_URL }}
        run: npm run test:e2e

      - name: Build the app
        env:
          VITE_EVBP_MUSIC_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          VITE_EVBP_MUSIC_CLOUDFLARE_TURNSTILE_SITE_KEY: ${{ secrets.CLOUDFLARE_TURNSTILE_SITE_KEY }}
          VITE_EVBP_MUSIC_CLOUDFLARE_TURNSTILE_SECRET_KEY: ${{ secrets.CLOUDFLARE_TURNSTILE_SECRET_KEY }}
        run: npm run build
