name: CI Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    env:
      VITE_EVBP_MUSIC_BASE_URL: ${{ secrets.BASE_URL }}
      VITE_EVBP_MUSIC_API_BASE_URL: ${{ secrets.API_BASE_URL }}
      VITE_EVBP_MUSIC_CLOUDFLARE_TURNSTILE_SITE_KEY: ${{ secrets.CLOUDFLARE_TURNSTILE_SITE_KEY }}
      VITE_EVBP_MUSIC_CLOUDFLARE_TURNSTILE_SECRET_KEY: ${{ secrets.CLOUDFLARE_TURNSTILE_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run unit tests
        run: npm run test

      - name: Start server
        run: nohup npm run dev > server.log 2>&1 &

      - name: Set dummy env for Dependabot
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: |
          echo "VITE_EVBP_MUSIC_BASE_URL=http://localhost:3000" >> $GITHUB_ENV
          echo "VITE_EVBP_MUSIC_API_BASE_URL=http://localhost:3001" >> $GITHUB_ENV

      - name: Verify environment variables
        run: node e2e_tests/setup/checkEnv.js

      - name: Debug BASE_URL
        run: |
          echo "Base URL: ${{ secrets.BASE_URL }}"

      - name: Wait for server to be ready
        run: npx wait-on ${{ secrets.BASE_URL }}

      - name: Run Cucumber tests
        run: npm run test:e2e

      - name: Build the app
        run: npm run build
